/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.luciano.vazquez.gestion_expedientes2.ui;

import com.luciano.vazquez.gestion_expedientes2.bo.AreaBO;
import com.luciano.vazquez.gestion_expedientes2.bo.ExpedienteBO;
import com.luciano.vazquez.gestion_expedientes2.bo.ExternoBO;
import com.luciano.vazquez.gestion_expedientes2.bo.TransicionBO;
import com.luciano.vazquez.gestion_expedientes2.bo.UsuarioBO;
import com.luciano.vazquez.gestion_expedientes2.entity.Expediente;
import com.luciano.vazquez.gestion_expedientes2.entity.Externo;
import com.luciano.vazquez.gestion_expedientes2.entity.Usuario;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Exo
 */
public class ExpedienteUI extends javax.swing.JPanel {

    /**
     * Creates new form MostrarExpediente
     */
    Usuario usuario;
    int idExpediente;
    Expediente expediente = new Expediente();
    ExpedienteBO expedienteBO = new ExpedienteBO();
    Externo externo = new Externo();
    ExternoBO externoBO = new ExternoBO();
    Usuario recupUsuario = new Usuario();
    UsuarioBO usuarioBO = new UsuarioBO();
    Usuario sesionUsuario = new Usuario();
    TransicionBO paseBO = new TransicionBO();
    AreaBO areaBO = new AreaBO();
    javax.swing.JPanel panel;
    javax.swing.JPanel panelSesion;
    MenuPrincipalUI panelMenu;
    TransicionUI panelTransicion;
    String a = "/";
    LocalDate dia = LocalDate.now();
    LocalTime hora = LocalTime.now();
    LocalDateTime fecha = LocalDateTime.of(dia, hora);

    public ExpedienteUI(javax.swing.JPanel panelContenedor, Usuario sesionUsuario, javax.swing.JPanel panelSesion, int idExpedienteSeleccion) {
        initComponents();
        this.panel = panelContenedor;
        this.usuario = sesionUsuario;
        this.idExpediente = idExpedienteSeleccion;
        this.panelSesion = panelSesion;
        
        System.out.println("FECHA:"+fecha);

        expediente = expedienteBO.buscarExpediente(idExpedienteSeleccion);
        externo = externoBO.buscarIniciante(expediente.getIdIniciante());
        recupUsuario = usuarioBO.buscarUsuario(expediente.getIdUsuario());

        //Carga de tabla con el historial de pases del expediente consultado
        paseBO.listarPases(jTable1, idExpediente);

        //Carga de componentes
        jLabelExpediente.setText(String.valueOf(expediente.getIdExpediente()) + a + String.valueOf(fecha.getYear()));

        if ((paseBO.obtenerUltimoPase(idExpediente)) != null) {
            //Expediente con pases previos
            jLabelObservacionPase.setText(paseBO.obtenerUltimoPase(idExpediente).getObservacion());
            jLabelAreaActual.setText(areaBO.obtenerNombreArea(paseBO.obtenerUltimoPase(idExpediente).getId_area_actual()));
            //No permitir que un usuario pueda realizar un pase de un expediente que no está en su posesión
            if (sesionUsuario.getIdUsuario() != paseBO.obtenerUltimoPase(idExpediente).getId_usuario_actual()) {
                jButtonPase.setEnabled(false);
                jButtonModificar.setEnabled(false);
            }
        } else {
            //expediente sin pases
            jLabelObservacionPase.setText("- Expediente sin pases previos -");
            jLabel1.setText("");
            jLabelAreaActual.setText(areaBO.obtenerNombreArea(recupUsuario.getIdArea()));
           
            if (sesionUsuario.getIdUsuario() != expediente.getIdUsuario()) {
                jButtonPase.setEnabled(false);
                jButtonModificar.setEnabled(false);
            }

        }

        jLabelEstado.setText(expediente.getEstado());
        jLabelFecha.setText(expediente.getFecha());
        jLabelRef.setText(expediente.getReferencia());
        jLabelTipo.setText(expediente.getTipo());
        jLabelUsuario.setText(recupUsuario.getNombre());
        if (expediente.getIdIniciante() == 0) {
            jLabel19.setText("Expediente");
            jLabelIniciante.setText("Interno");
            jButtonContacto.setEnabled(false);
        } else {
            jLabelIniciante.setText(externo.getNombre() + " " + externo.getApellido());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always *
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAreaActual = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonMenu = new javax.swing.JButton();
        jButtonPase = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelIniciante = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelRef = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jButtonContacto = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButtonModificar = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelExpediente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelObservacionPase = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabelAreaActual.setText("Espacios Verdes");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Iniciante:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Expediente N°:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Origen ", "Destino", "Enviado por usuario", "Recibido por usuario", "Estado", "Situación", "Fecha de pase", "Observación", "Fojas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonMenu.setText("Menú Principal");
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });

        jButtonPase.setText("Realizar Transición");
        jButtonPase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaseActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Estado: ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Iniciado el: ");

        jLabelIniciante.setText("Lisandro Tevez");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Tipo: ");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Referencia:");

        jLabelEstado.setText("Resuelto");

        jLabelRef.setText("Reclamo por arbol caído en calle San Martín esq. calle Belgrano, B° Leandro Alem. ");

        jLabelFecha.setText("10/11/2020");

        jButtonContacto.setText("Contacto");
        jButtonContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContactoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("por Usuario:");

        jButtonModificar.setText("Modificar Información");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jLabelUsuario.setForeground(new java.awt.Color(51, 102, 255));
        jLabelUsuario.setText("Pedro Leiva");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Historial de Movimientos");

        jLabelTipo.setText("Reclamo (Externo)");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Area Actual: ");

        jLabelExpediente.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelExpediente.setText("XXX");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Observación último pase:");

        jLabelObservacionPase.setText("jLabel2");

        jButton1.setText("Carátula");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelRef))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelTipo)
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelAreaActual)
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelEstado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelIniciante)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelExpediente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelFecha)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelUsuario))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelObservacionPase)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jButtonMenu)
                                .addGap(89, 89, 89)
                                .addComponent(jButtonPase)
                                .addGap(78, 78, 78)
                                .addComponent(jButtonModificar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jLabel23)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(jLabelFecha)
                    .addComponent(jLabel14)
                    .addComponent(jLabelUsuario)
                    .addComponent(jLabelExpediente)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabelTipo)
                    .addComponent(jLabel19)
                    .addComponent(jLabelIniciante)
                    .addComponent(jButtonContacto)
                    .addComponent(jLabel9)
                    .addComponent(jLabelEstado)
                    .addComponent(jLabel17)
                    .addComponent(jLabelAreaActual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabelRef))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelObservacionPase))
                .addGap(9, 9, 9)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMenu)
                    .addComponent(jButtonPase)
                    .addComponent(jButtonModificar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        int b;

        b = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea regresar al Menú Principal?",
                "Advertencia", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (b == 0) {
            panelMenu = new MenuPrincipalUI(panel, usuario, panelSesion);
            panel.add(panelMenu);
            panelMenu.setVisible(true);
            this.setVisible(false);
        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonPaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaseActionPerformed
        panelTransicion = new TransicionUI(panel, usuario, panelSesion, idExpediente);
        panel.add(panelTransicion);
        panelTransicion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonPaseActionPerformed

    private void jButtonContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonContactoActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed

    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Process p = Runtime.getRuntime().exec("rundll32 SHELL32.DLL,ShellExec_RunDLL " + "C:\\Users\\Exo\\Desktop\\EFIP 1\\SISTEMA\\caratula.pdf");
        } catch (IOException ex) {
            Logger.getLogger(ExpedienteUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonContacto;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonPase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAreaActual;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelExpediente;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelIniciante;
    private javax.swing.JLabel jLabelObservacionPase;
    private javax.swing.JLabel jLabelRef;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
