/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.luciano.vazquez.gestion_expedientes2.ui;

import com.luciano.vazquez.gestion_expedientes2.bo.UsuarioBO;
import com.luciano.vazquez.gestion_expedientes2.entity.Usuario;
import javax.swing.JOptionPane;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JPanel;

/**
 *
 * @author Exo
 */
public class PanelSesionUI extends javax.swing.JPanel {

    /**
     * Creates new form PanelSesion
     */
    GridBagLayout layaout = new GridBagLayout();
    Usuario usuario;
    UsuarioBO usuarioBO = new UsuarioBO();
    LoginUI login;
    
    javax.swing.JPanel panelContenedor;
    javax.swing.JPanel panelContenedorSesion;
    PanelUsuarioUI panelUsuario;
    
    public PanelSesionUI(javax.swing.JPanel panelContenedor, javax.swing.JPanel panelContenedorSesion, Usuario sesionUsuario) {
        initComponents();
        this.usuario = sesionUsuario;
        this.panelContenedor = panelContenedor;
        this.panelContenedorSesion = panelContenedorSesion;
        
        System.out.println("" + usuario.getNombre());
        jButtonUsuario.setVisible(true);
        jButtonUsuario.setText(usuario.getNombre());
        jButtonUsuario.setEnabled(true);
        jButtonCerrarSesion.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSesion = new javax.swing.JPanel();
        jButtonUsuario = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonCerrarSesion = new javax.swing.JButton();

        jPanelSesion.setPreferredSize(new java.awt.Dimension(800, 72));

        jButtonUsuario.setFont(new java.awt.Font("Candara", 1, 13)); // NOI18N
        jButtonUsuario.setForeground(new java.awt.Color(102, 102, 255));
        jButtonUsuario.setText("Usuario");
        jButtonUsuario.setBorder(null);
        jButtonUsuario.setBorderPainted(false);
        jButtonUsuario.setContentAreaFilled(false);
        jButtonUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUsuario.setFocusPainted(false);
        jButtonUsuario.setName(""); // NOI18N
        jButtonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuarioActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("SISTEMA DE SEGUIMIENTO DE EXPEDIENTES");

        jLabel5.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("MUNICIPALIDAD DE SUIPACHA");

        jLabel1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel1.setText("Usuario Actual:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logosuipacha.png"))); // NOI18N

        jButtonCerrarSesion.setText("Cerrar Sesion");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSesionLayout = new javax.swing.GroupLayout(jPanelSesion);
        jPanelSesion.setLayout(jPanelSesionLayout);
        jPanelSesionLayout.setHorizontalGroup(
            jPanelSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSesionLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(jPanelSesionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonUsuario)
                .addGap(171, 171, 171)
                .addComponent(jButtonCerrarSesion)
                .addGap(30, 30, 30))
        );
        jPanelSesionLayout.setVerticalGroup(
            jPanelSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSesionLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelSesionLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addGroup(jPanelSesionLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanelSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jButtonUsuario)
                            .addComponent(jButtonCerrarSesion))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuarioActionPerformed
        
        panelUsuario = new PanelUsuarioUI(panelContenedor, usuario, panelContenedorSesion);
        
        
        
        
         int i = panelContenedor.getComponentCount();
        while (i != 0) {
            if (panelContenedor.getComponent(i-1) instanceof JPanel) {
                panelContenedor.getComponent(i-1).setVisible(false);
            }
            i--;
        }
        
        panelContenedor.add(panelUsuario);
        panelUsuario.setVisible(true);
        
       
        

    }//GEN-LAST:event_jButtonUsuarioActionPerformed

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
  int b;
        
        b = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea cerrar sesión?",
                "Advertencia", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (b == 0) {
            
            jButtonUsuario.setText("");
            jButtonUsuario.setEnabled(false);
             int i = panelContenedor.getComponentCount();
        while (i != 0) {
            if (panelContenedor.getComponent(i-1) instanceof JPanel) {
                panelContenedor.getComponent(i-1).setVisible(false);
            }
            i--;
        }
            login = new LoginUI(panelContenedor, jPanelSesion);
            
            panelContenedor.setLayout(layaout);
            GridBagConstraints c = new GridBagConstraints();
            c.gridx = 0;
            c.gridy = 0;
            panelContenedor.add(login, c);
            login.setVisible(true);
            jButtonCerrarSesion.setEnabled(false);
            

            //this.setContentPane(jPanelFondo);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelSesion;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
