/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.luciano.vazquez.gestion_expedientes2.ui;

import com.luciano.vazquez.gestion_expedientes2.bo.AreaBO;
import com.luciano.vazquez.gestion_expedientes2.bo.ExpedienteBO;
import com.luciano.vazquez.gestion_expedientes2.bo.ExternoBO;
import com.luciano.vazquez.gestion_expedientes2.bo.TransicionBO;
import com.luciano.vazquez.gestion_expedientes2.bo.UsuarioBO;
import com.luciano.vazquez.gestion_expedientes2.entity.Area;
import com.luciano.vazquez.gestion_expedientes2.entity.Expediente;
import com.luciano.vazquez.gestion_expedientes2.entity.Externo;
import com.luciano.vazquez.gestion_expedientes2.entity.Transicion;
import com.luciano.vazquez.gestion_expedientes2.entity.Usuario;
import java.awt.event.ItemEvent;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Exo
 */
public class TransicionUI extends javax.swing.JPanel {

    /**
     * Creates new form Transicion
     */
    Usuario usuario;
    int idExpediente;
    ExpedienteBO expedienteBO = new ExpedienteBO();
    Expediente expediente = new Expediente();
    UsuarioBO usuarioBO = new UsuarioBO();
    Usuario recupUsuario = new Usuario();
    AreaBO areaBO = new AreaBO();
    Area area = new Area();
    Externo externo = new Externo();
    ExternoBO externoBO = new ExternoBO();
    ArrayList<String> usuariosList = new ArrayList();
    TransicionBO paseBO = new TransicionBO();
    Transicion pase = new Transicion();

    javax.swing.JPanel panel;
    MenuPrincipalUI panelMenu;
    javax.swing.JPanel panelSesion;
    TransicionUI panelTransicion;
    ExpedienteUI panelExpediente;
    String a = "/";
    String area_actual;
    LocalDate dia = LocalDate.now();
    LocalTime hora = LocalTime.now();
    LocalDateTime fecha = LocalDateTime.of(dia, hora);

    public TransicionUI(javax.swing.JPanel panelContenedor, Usuario sesionUsuario, javax.swing.JPanel panelSesion, int idExpediente) {
        initComponents();
        this.panel = panelContenedor;
        this.usuario = sesionUsuario;
        this.idExpediente = idExpediente;
        this.panelSesion = panelSesion;

        expediente = expedienteBO.buscarExpediente(idExpediente);
        recupUsuario = usuarioBO.buscarUsuario(expediente.getIdUsuario());
        externo = externoBO.buscarIniciante(expediente.getIdIniciante());

        jLabelNroExpediente.setText(String.valueOf(idExpediente + a + String.valueOf(fecha.getYear())));
        jLabelUsuarioIniciante.setText(recupUsuario.getNombre());
        jLabelFechaAlta.setText(expediente.getFecha());

        if (expediente.getIdIniciante() == 0) {
            jLabel19.setText("Expediente");
            jLabelIniciante.setText("Interno");

        } else {
            jLabelIniciante.setText(externo.getNombre() + " " + externo.getApellido());
        }

        if (paseBO.obtenerUltimoPase(idExpediente) == null) {
            //El expediente no tiene pases todavía
            jLabelEstadoActual.setText(expediente.getEstado());
            jLabelSituacionActual.setText("");
            jLabel17.setText("");
            jLabelAreaActual.setText(areaBO.obtenerNombreArea(recupUsuario.getIdArea()));
            jComboBoxAreaDestino.removeItem(areaBO.obtenerNombreArea(recupUsuario.getIdArea()));
        } else {
            area_actual = areaBO.obtenerNombreArea(paseBO.obtenerUltimoPase(idExpediente).getId_area_actual());
            jLabelSituacionActual.setText(paseBO.obtenerUltimoPase(idExpediente).getSituacion());
            //comprob que no se puede elegir como Area destino el area actual
            jComboBoxAreaDestino.removeItem(area_actual);
            jLabelAreaActual.setText(area_actual);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxUsuarioDestino = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxSituacion = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelEstadoActual = new javax.swing.JLabel();
        jLabelFechaAlta = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelUsuarioIniciante = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelSituacionActual = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObservaciones = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldFojas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabelIniciante = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButtonCancelar = new javax.swing.JButton();
        jButtonGenerarPase = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxAreaDestino = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabelNroExpediente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelAreaActual = new javax.swing.JLabel();

        jComboBoxUsuarioDestino.setMaximumRowCount(4);
        jComboBoxUsuarioDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Situación:");

        jComboBoxSituacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Para Autorizar", "Para Conocimiento", "Para Protocolizar", "Para Resolución", "Para Corregir", "Para Adjuntar Documentación", "Para Archivar", "Para Pago", " ", " " }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Estado Actual: ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Iniciado el: ");

        jLabelEstadoActual.setText("Resuelto");

        jLabelFechaAlta.setText("10/11/2020");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("por Usuario:");

        jLabelUsuarioIniciante.setForeground(new java.awt.Color(51, 102, 255));
        jLabelUsuarioIniciante.setText("Pedro Leiva");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Situación Actual: ");

        jLabelSituacionActual.setText("Pago realizado");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Iniciante:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Observaciones:");

        jTextAreaObservaciones.setColumns(20);
        jTextAreaObservaciones.setRows(5);
        jScrollPane1.setViewportView(jTextAreaObservaciones);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Fojas:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Transición Expediente N° ");

        jLabelIniciante.setText("Lisandro Tevez");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonGenerarPase.setText("Generar Transición");
        jButtonGenerarPase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarPaseActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Área de Destino:");

        jComboBoxAreaDestino.setMaximumRowCount(5);
        jComboBoxAreaDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Mesa de Entradas", "Secretaría de Gobierno", "Secretaría de Hacienda", "Dirección de Contaduría", "Secretaría de Obras Públicas", "Secretaría de Acción Social", " ", " " }));
        jComboBoxAreaDestino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxAreaDestinoItemStateChanged(evt);
            }
        });
        jComboBoxAreaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAreaDestinoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Usuario que recibe:");

        jLabelNroExpediente.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelNroExpediente.setText("XXX");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Área Actual:");

        jLabelAreaActual.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxAreaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxUsuarioDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 55, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel23)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCancelar)
                                .addGap(99, 99, 99)
                                .addComponent(jButtonGenerarPase)
                                .addGap(22, 22, 22)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFojas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSituacion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelFechaAlta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelUsuarioIniciante)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelIniciante))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEstadoActual)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSituacionActual)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAreaActual))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel4)
                                .addGap(6, 6, 6)
                                .addComponent(jLabelNroExpediente)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelNroExpediente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelFechaAlta)
                    .addComponent(jLabel14)
                    .addComponent(jLabelUsuarioIniciante)
                    .addComponent(jLabelIniciante)
                    .addComponent(jLabel19))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSituacionActual)
                    .addComponent(jLabel9)
                    .addComponent(jLabelEstadoActual)
                    .addComponent(jLabel17)
                    .addComponent(jLabel1)
                    .addComponent(jLabelAreaActual))
                .addGap(22, 22, 22)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxAreaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBoxUsuarioDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jComboBoxSituacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jTextFieldFojas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonGenerarPase))
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int b;

        b = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea cancelar la transición del expediente?. Se perderán los datos ingresados.",
                "Advertencia", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (b == 0) {
            panelExpediente = new ExpedienteUI(panel, usuario, panelSesion, idExpediente);
            panel.add(panelExpediente);
            panelExpediente.setVisible(true);
            this.setVisible(false);
        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonGenerarPaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarPaseActionPerformed
        String situacion = (String) (jComboBoxSituacion.getSelectedItem());
        String area_siguiente = (String) (jComboBoxAreaDestino.getSelectedItem());
        String usuario_siguiente = (String) (jComboBoxUsuarioDestino.getSelectedItem());

        System.out.println("SITUACION"+situacion);
        System.out.println("ESTADO"+expediente.getEstado());
        
        /*SWITCH para actualizar el estado de acuerdo a la actualizacion de la situacion ingresada en el pase*/
        switch (situacion) {
            case "Para Autorizar":
                expediente.setEstado("En trámite");
                break;
            case "Para Conocimiento":
                expediente.setEstado("En trámite");
                break;
            case "Para Resolución":
                expediente.setEstado("En trámite");
                break;
            case "Para Protocolizar":
                expediente.setEstado("Resuelto");
                break;
            case "Para Pago":
                expediente.setEstado("Resuelto");
                break;
            case "Para Corregir":
                expediente.setEstado("Subsanación");
                break;
            case "Para Adjuntar Documentación":
                expediente.setEstado("Subsanación");
                break;
            case "Para Archivar":
                expediente.setEstado("Archivado");
                break;
            default:
                expediente.setEstado("En trámite");
        }
        
        // ACTUALIZO ESTADO EN BASE DE DATOS 
        expedienteBO.update(expediente);
        
        //CARGO NUEVO PASE
        pase.setIdExpediente(idExpediente);
        pase.setFecha(String.valueOf(fecha));
        pase.setSituacion(situacion);
        pase.setObservacion(jTextAreaObservaciones.getText());
        pase.setFojas(Integer.parseInt(jTextFieldFojas.getText()));

        pase.setId_area_actual(areaBO.obtenerIdArea(area_siguiente));
        pase.setId_usuario_actual(usuarioBO.obtenerIdUsuario(usuario_siguiente));

        if (paseBO.obtenerUltimoPase(idExpediente) == null) {
            //El expediente no tiene pases todavía, se recuperan datos del usuario y area que inicio
            System.out.println("ID 1er pase:" + recupUsuario.getIdUsuario());
            pase.setId_area_anterior(recupUsuario.getIdArea());
            pase.setId_usuario_anterior(recupUsuario.getIdUsuario());

            paseBO.insert(pase);

        } else {
            //EL expediente tiene pases previos, se recupera valores del último
            System.out.println("ID pase Anterior:" + paseBO.obtenerUltimoPase(idExpediente).getId_usuario_anterior());
            pase.setId_area_anterior(paseBO.obtenerUltimoPase(idExpediente).getId_area_actual());
            pase.setId_usuario_anterior(paseBO.obtenerUltimoPase(idExpediente).getId_usuario_actual());
            paseBO.insert(pase);
        }
        JOptionPane.showMessageDialog(null, "El nuevo pase se ha realizado correctamente.");

        panelExpediente = new ExpedienteUI(panel, usuario, panelSesion, idExpediente);
        panel.add(panelExpediente);
        panelExpediente.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButtonGenerarPaseActionPerformed

    private void jComboBoxAreaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAreaDestinoActionPerformed

    }//GEN-LAST:event_jComboBoxAreaDestinoActionPerformed

    private void jComboBoxAreaDestinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxAreaDestinoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            jComboBoxUsuarioDestino.removeAllItems();

            areaBO = new AreaBO();
            System.out.println("" + String.valueOf(jComboBoxAreaDestino.getSelectedItem()));
            usuariosList = areaBO.ObtenerUsuariosList(String.valueOf(jComboBoxAreaDestino.getSelectedItem()));

            for (int i = 0; i < usuariosList.size(); i++) {
                jComboBoxUsuarioDestino.addItem(usuariosList.get(i));
            }
        }
    }//GEN-LAST:event_jComboBoxAreaDestinoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGenerarPase;
    private javax.swing.JComboBox<String> jComboBoxAreaDestino;
    private javax.swing.JComboBox<String> jComboBoxSituacion;
    private javax.swing.JComboBox<String> jComboBoxUsuarioDestino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAreaActual;
    private javax.swing.JLabel jLabelEstadoActual;
    private javax.swing.JLabel jLabelFechaAlta;
    private javax.swing.JLabel jLabelIniciante;
    private javax.swing.JLabel jLabelNroExpediente;
    private javax.swing.JLabel jLabelSituacionActual;
    private javax.swing.JLabel jLabelUsuarioIniciante;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextAreaObservaciones;
    private javax.swing.JTextField jTextFieldFojas;
    // End of variables declaration//GEN-END:variables
}
